import Head from 'next/head'
import Image from 'next/image'
import { useSession } from 'next-auth/react'

export default function Home() {
  const { data: session, status } = useSession()
  const loading = status === 'loading'
  console.log(status)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1>Index page</h1>
        <p>{session ? `${status}, ` : `${status}`} Welcome to{'NextJS'}</p>
      </main>

    </div>
  )
}
